# ./docker-compose.yml

version: '2'
 
services:
    ubuntu:
        image: ubuntu:latest
        volumes:
            - ./web:/var/www/html
 
    php:
        build:
            context: ./etc/php
        ports:
            - 9000:9000
        volumes_from:
            - ubuntu
        volumes:
            - ./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
 
    nginx:
        image: nginx:latest
        ports:
            - 9999:80
        volumes_from:
            - ubuntu
        volumes:
            - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    myadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        ports:
            - '8080:80'
 
    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
            - 3306:3306
        links:
            - php
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        restart: always
        volumes:
            - ./data/db/mysql:/var/lib/mysql
